### ISSUE TITLE
Deployment with Windows bootstrap node: `CTRL_C` event is not sent

### ISSUE THREAD

**Issue by ionutbalutoiu** [dcos/dcos-windows#134]
The systemd service wrapper is not sending `CTRL_C` to the child processes.

I tried to stop the Mesos service on Windows via `Stop-Service dcos-mesos-slave-public.service` and if I didn't notice this in the mesos-agent log:

```
I0821 17:26:49.220176  2404 slave.cpp:952] Received SIGUSR1 signal; unregistering and shutting down
I0821 17:26:49.220176  2404 slave.cpp:909] Agent terminating
2018-08-21 17:26:49,222:392(0x101c):ZOO_INFO@zookeeper_close@2562: Closing zookeeper sessionId=0x1655c71ffa20038 to [192.168.255.5:2181]

I0821 17:26:49.224193  4476 process.cpp:926] Stopped the socket accept loop
```

The `Received SIGUSR1` should be logged if the `mesos-agent.exe` process gets the `CTRL_C` event.

**Comment by yakman2020** [comment]
This is addressed by pr 131

**Comment by ionutbalutoiu** [comment]
Fixed in Pkgpanda by https://github.com/paulcallen/dcos/commit/90190cd1920ff5e305f10447be52dcaee41fde5e
