### ISSUE TITLE
DC/OS deployment issue: Update-AzureRmVmss failure

### ISSUE THREAD

**Issue by soccerGB** [dcos/dcos-windows#52]
# Symptom:
    Another transient error in Update-AzureRmVMss call, it fails sometimes.

# Log information

Snippet directly from the log:

   case 1:
    Update-AzureRmVmss : A task was canceled.
    At C:\Jenkins\workspace\dcos-testing-autoscale\DCOS\autoscale-testing\AutoScale.Tests.ps1:200 char:16
    + ...      $res = Update-AzureRmVmss -ResourceGroupName $RG_NAME -Name $sca ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : CloseError: (:) [Update-AzureRmVmss], TaskCanceledException
        + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss

        [-] Can increase the scaleset capacity 233.99s
          Expected $null to be different from the actual value, but got the same value.
          201:         $res | Should not be $null
          at Invoke-LegacyAssertion, C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Functions\Assertions\Should.ps1: line 188
          at <ScriptBlock>, C:\Jenkins\workspace\dcos-testing-autoscale\DCOS\autoscale-testing\AutoScale.Tests.ps1: line 201
   
   Case 2:
    w71922901-vmss
    Update-AzureRmVmss : Long running operation failed with status 'Failed'. Additional Info:'An internal execution error 
    occurred.'
    ErrorCode: InternalExecutionError
    ErrorMessage: An internal execution error occurred.
    StartTime: 4/26/2018 9:13:36 PM
    EndTime: 4/26/2018 9:35:50 PM
    OperationID: 0b45f40d-527d-4e32-a8ee-5446c945705d
    Status: Failed
    At C:\Jenkins\workspace\dcos-testing-autoscale\DCOS\autoscale-testing\AutoScale.Tests.ps1:315 char:16
    + ...      $res = Update-AzureRmVmss -ResourceGroupName $RG_NAME -Name $sca ...
    +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : CloseError: (:) [Update-AzureRmVmss], ComputeCloudException
        + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss

        [-] Can reduce the scaleset capacity 1356.11s
          Expected $null to be different from the actual value, but got the same value.
          316:         $res | Should not be $null
          at Invoke-LegacyAssertion, C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Functions\Assertions\Should.ps1: line 188
          at <ScriptBlock>, C:\Jenkins\workspace\dcos-testing-autoscale\DCOS\autoscale-testing\AutoScale.Tests.ps1: line 316

          
# Status
      Active

**Comment by ionutbalutoiu** [comment]
I haven't seen this issue at all after the scale tests clean-up committed with:

- https://github.com/Microsoft/mesos-jenkins/pull/62
- https://github.com/Microsoft/mesos-jenkins/commit/a4b8aa263195ef6b2b3aab4469077f93679e34ad

I will re-open the issue if I see it reproduced again.
