### ISSUE TITLE
DC/OS deployment failure: VMExtensionProvisioningTimeout: Provisioning of VM extension 'waitforleader' has timed out

### ISSUE THREAD

**Issue by soccerGB** [dcos/dcos-windows#54]
....
Failed: waitforleader (Microsoft.Compute/virtualMachines/extensions)
Failed: azuredeploy (Microsoft.Resources/deployments)
Deployment failed. Correlation ID: acb7fb12-6457-41ab-93fd-0b706460f925. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMExtensionProvisioningTimeout",
        "message": "Provisioning of VM extension 'waitforleader' has timed out. Extension installation may be taking too long, or extension status could not be obtained."
      }
    ]
  }
}

**Comment by soccerGB** [comment]
We got a little but further on the “waitforleader” issue. The docker.socket failed is the source of this failure. it looks like timing issue and we are still investigating its root cause.

azureuser@dcos-master-81849083-0:~$ systemctl list-units --state=failed
  UNIT                    LOAD   ACTIVE SUB    DESCRIPTION
● hv-fcopy-daemon.service loaded failed failed Hyper-V File Copy Protocol Daemon
● docker.socket           loaded failed failed docker.socket

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

2 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
azureuser@dcos-master-81849083-0:~$ systemctl status docker.socket
● docker.socket
   Loaded: loaded (/etc/systemd/system/docker.socket; enabled; vendor preset: enabled)
   Active: failed (Result: resources) since Thu 2018-05-03 01:52:51 UTC; 15h ago
   Listen: /var/run/docker.sock (Stream)
           [::]:2375 (Stream)

May 03 01:52:51 dcos-master-81849083-0 systemd[1]: Starting docker.socket.
May 03 01:52:51 dcos-master-81849083-0 systemd[1]: Listening on docker.socket.
May 03 01:52:51 dcos-master-81849083-0 systemd[1]: Closed docker.socket.
May 03 01:52:51 dcos-master-81849083-0 systemd[1]: Stopping docker.socket.
May 03 01:52:51 dcos-master-81849083-0 systemd[1]: docker.socket: Failed to listen on sockets: Address already in use
May 03 01:52:51 dcos-master-81849083-0 systemd[1]: Failed to listen on docker.socket.
May 03 01:52:51 dcos-master-81849083-0 systemd[1]: docker.socket: Unit entered failed state

**Comment by soccerGB** [comment]
This issue was fixed by https://github.com/Azure/acs-engine/pull/2865 for the acs-engine repor

**Comment by soccerGB** [comment]
We thought this was gone  with the above acs-engine change for bringing in bootstrapnode set. 
But we hit a repro today.

**Comment by ionutbalutoiu** [comment]
Debugging the failed resource group further, I found this:

```
  File "/opt/mesosphere/bin/bootstrap", line 11, in <module>
    load_entry_point('dcos-internal-utils==0.0.1', 'console_scripts', 'bootstrap')()
  File "/opt/mesosphere/lib/python3.6/site-packages/dcos_internal_utils/cli.py", line 94, in main
    exhibitor.wait(opts.master_count)
  File "/opt/mesosphere/lib/python3.6/site-packages/dcos_internal_utils/exhibitor.py", line 113, in wait
    raise Exception(msg_fmt.format(cluster_size, len(serving), len(leaders)))
Exception: Expected 3 servers and 1 leader, got 2 servers and 1 leaders
```

The provisioning failed because 1 of the 3 masters to be deployed didn’t come up successfully.

I’ve logged into the failing master and checked the cloud-init log at from `/var/log/cloud-init-output.log`:

```
Checking if port 61053 (required by mesos-dns) is in use: PASS
Checking if port 61091 (required by dcos-metrics) is in use: PASS
Checking if port 61420 (required by dcos-net) is in use: PASS
Checking if port 62080 (required by dcos-net) is in use: PASS
Checking if port 62501 (required by dcos-net) is in use: PASS
Checking Docker is configured with a production storage driver: /tmp/dcos/dcos_install.sh: line 324: docker: command not found
PASS ()
Preflight checks failed. Exiting installation. Please consult product documentation
Cloud-init v. 18.2 running 'modules:final' at Wed, 16 May 2018 21:15:49 +0000. Up 45.33 seconds.
Cloud-init v. 18.2 finished at Wed, 16 May 2018 21:18:16 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 192.80 seconds
```

It seems to be failing at "Checking Docker is configured with a production storage driver" when executing /tmp/dcos/dcos_install.sh.

This is not happening on the other masters. This is how cloud-init log looks on the successful masters installation:

```
Checking if port 61420 (required by dcos-net) is in use: PASS
Checking if port 62080 (required by dcos-net) is in use: PASS
Checking if port 62501 (required by dcos-net) is in use: PASS
Checking Docker is configured with a production storage driver: WARNING: No swap limit support
PASS (overlay)
Creating directories under /etc/mesosphere
Creating role file for master
Configuring DC/OS
Setting and starting DC/OS
Created symlink from /etc/systemd/system/multi-user.target.wants/dcos-setup.service to /etc/systemd/system/dcos-setup.service.
Cloud-init v. 18.2 running 'modules:final' at Wed, 16 May 2018 21:16:21 +0000. Up 52.06 seconds.
Cloud-init v. 18.2 finished at Wed, 16 May 2018 21:20:32 +0000. Datasource DataSourceAzure [seed=/dev/sr0].  Up 303.38 seconds
```

It just prints a warning and everything moves on.

**Comment by ionutbalutoiu** [comment]
It turned out that Docker is not properly initialized and that's why we get the above error on the failing master. This acs-engine PR https://github.com/Azure/acs-engine/pull/3009/ is addressing this ssue.

**Comment by soccerGB** [comment]
The PR Azure/acs-engine#3009 has been merged into the acs-engine master. 
Let's give it a few days to see if this issue is completely gone before re-solving this issue.

**Comment by ionutbalutoiu** [comment]
Everything looks good in the CI with the new acs-engine patch. Closing this issue.
