### ISSUE TITLE
RS3 only: Public port for the IIS is not accessible outside Azure even though the task is healthy

### ISSUE THREAD

**Issue by ionutbalutoiu** [dcos/dcos-windows#59]
This transient failure was reproduced in the following Jenkins jobs runs:

- https://mesos-jenkins.westus.cloudapp.azure.com/job/dcos-testing/541/console
- https://mesos-jenkins.westus.cloudapp.azure.com/job/dcos-testing/553/console
- https://mesos-jenkins.westus.cloudapp.azure.com/job/dcos-testing/558/console
- https://mesos-jenkins.westus.cloudapp.azure.com/job/dcos-testing/560/console
- https://mesos-jenkins.westus.cloudapp.azure.com/job/dcos-testing/561/console

**Comment by soccerGB** [comment]
This issue turned out to be a known Windows RS3 networking issue, which has been fixed in RS4.

**Comment by soccerGB** [comment]
We are moving away from RS3 because issue like this one only got fixed in the RS4
