### ISSUE TITLE
Failed to clean-up vcredist_x64.exe installer

### ISSUE THREAD

**Issue by ionutbalutoiu** [dcos/dcos-windows#60]
During the `dcos-net` setup step, the initialization script sometimes fails when trying to do cleanup after the install of `vcredist_x64.exe` is complete.

This is the failing line: https://github.com/dcos/dcos-windows/blob/master/scripts/dcos-net-agent-setup.ps1#L33

Snippet from the `DCOSWindowsAgentSetup.log` log:

```
Install VCredist: https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe
Finished to install VCredist: https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x64.exe
Install VCredist: https://download.visualstudio.microsoft.com/download/pr/11687625/2cd2dba5748dc95950a5c42c2d2d78e4/VC_redist.x64.exe
Finished to install VCredist: https://download.visualstudio.microsoft.com/download/pr/11687625/2cd2dba5748dc95950a5c42c2d2d78e4/VC_redist.x64.exe
Cannot remove item C:\Windows\TEMP\vcredist_x64.exe: Access to the path 'C:\Windows\TEMP\vcredist_x64.exe' is denied.
Failed to setup the dcos-net Windows agent
The upstream DCOS init script failed
at <ScriptBlock>, C:\AzureData\DCOSWindowsAgentSetup.ps1: line 126
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, C:\AzureData\dcosWindowsProvision.ps1: line 200
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1
Failed to initialize the DCOS node for CI
```

It looks like some process it's still using the `vcredist_x64.exe` installer, even after the installation is complete and gives the error:

```
Cannot remove item C:\Windows\TEMP\vcredist_x64.exe: Access to the path 'C:\Windows\TEMP\vcredist_x64.exe' is denied.
```

It is recommended to check if any process is using any of the files that we want to cleanup. A pull request will follow to achieve this.

**Comment by soccerGB** [comment]
Fixed by https://github.com/dcos/dcos-windows/pull/62

**Comment by ionutbalutoiu** [comment]
Reproduced yesterday for:

* http://dcos-win.westus.cloudapp.azure.com/dcos-testing/809/windows_agents/10.1.0.8/AzureData/DCOSWindowsAgentSetup.log

**Comment by aserdean** [comment]
I sent out two PRs:
https://github.com/dcos/dcos-windows/pull/99
https://github.com/dcos/dcos-windows/pull/100
please take a look when you find time :)
