### ISSUE TITLE
DC/OS-NET issue when the Windows agent's vm size has greater than 16 CPU cores

### ISSUE THREAD

**Issue by soccerGB** [dcos/dcos-windows#68]
When using Standard_D32_v3 Azure VM as Windows agent machine, DNS stops working reliably.
This was the DNS issue that Paul was hitting in his PkgPanda deployment work.

**Comment by soccerGB** [comment]
The PR in https://github.com/dcos/dcos-windows/pull/67 addresses this issue.

**Comment by ionutbalutoiu** [comment]
PR with the fix is merged. Closed this issue.
