### ISSUE TITLE
All DCOS deployment failed during the DCOS-NEt setup

### ISSUE THREAD

**Issue by soccerGB** [dcos/dcos-windows#77]
100% repro on the latest dcos-windows+acs-engine  during Window agent node provisioning:

Creating the dcos-net network device
The term '5/31/2018 8:47 PM: Start-ExecuteWithRetry attempt 0 5/31/2018 8:47 PM: Start-ExecuteWithRetry completed C:\Windows\TEMP\devcon.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
5/31/2018 8:48 PM: Error in setting up DCOS Windows Agent: Failed to setup the dcos-net Windows agent.ToString()

**Comment by ionutbalutoiu** [comment]
This is fixed by https://github.com/dcos/dcos-windows/pull/78

I can confirm the stability of the CI after the above PR was merged.

Ionut
